# Generated by Django 4.2.1 on 2023-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nom_cargo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='app_cli',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nom_cli',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='raz_sol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nom_com',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='app',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='num_celu',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='espacio_bodega',
            name='columna',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nom_esp',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='nom_fer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='cod_postal',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='macetero',
            name='tamanno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='macetero',
            name='tipo_macetero',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nom_pais',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nom_planta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nom_prov',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nom_prov',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom_region',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nom_sucursal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='temporada',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_pago',
            name='nom_tipo_pago',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tipofer',
            name='especificacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tipofer',
            name='tipo_fer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
