# Generated by Django 4.2.1 on 2023-05-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cargo_nom_cargo_alter_cliente_app_cli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_despacho',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_prod',
            field=models.IntegerField(null=True, verbose_name=6),
        ),
    ]
