# Generated by Django 4.2.1 on 2023-05-31 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_bodega_id_prod_alter_boleta_id_boleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='opcion_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('despacho', 'Despacho')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.sucursal'),
        ),
    ]
