# Generated by Django 4.2.1 on 2023-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_provincia_nom_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='opcion_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('despacho', 'Despacho')], max_length=30, null=True),
        ),
    ]
